spring:
  datasource:
    #      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
#    password: Homega2016@@@
    password: 78599297
mybatis:
  mapperLocations: classpath:/mapper/*.xml
server:
  port: 8888
